version: '3.7'

services:
  app:
    build: .
    image: djangogirls-dev
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - "8000:8000"
