version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - type: bind
        source: ./data/db
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    image: djangogirls-dev
    command: python3 manage.py runserver_plus 0.0.0.0:8000
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
